
BLOCK_STATE_ACTIVATE = 'block_state_activate'
BLOCK_STATE_FADING = 'block_state_fading'
BLOCK_STATE_DEACTIVATE = 'block_state_deactivate'

BLOCK_TYPE_TRANSMITTER = 'block_type_transmitter'
BLOCK_TYPE_OUTPUT = 'block_type_output'
BLOCK_TYPE_INPUT = 'block_type_input'
BLOCK_TYPE_REGULATOR = 'block_type_regulator'
BLOCK_TYPE_TRIGGER = 'block_type_trigger_block'
BLOCK_TYPE_TRIGGER_LOCKED = 'block_type_trigger_block_locked'

ALL_BLOCK_TYPES = [
    BLOCK_TYPE_TRANSMITTER,
    BLOCK_TYPE_OUTPUT,
    BLOCK_TYPE_INPUT,
    BLOCK_TYPE_REGULATOR,
    BLOCK_TYPE_TRIGGER,
    BLOCK_TYPE_TRIGGER_LOCKED,
]

ALLOW_DELETE_BLOCK_TYPES = [
    BLOCK_TYPE_TRANSMITTER,
    BLOCK_TYPE_REGULATOR,
    BLOCK_TYPE_TRIGGER,
    BLOCK_TYPE_TRIGGER_LOCKED,
]

ALLOW_CREATE_BLOCK_TYPES = [
    BLOCK_TYPE_TRANSMITTER,
    BLOCK_TYPE_TRANSMITTER,
    BLOCK_TYPE_REGULATOR,
    BLOCK_TYPE_TRIGGER,
    BLOCK_TYPE_TRIGGER_LOCKED,
]